[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra -q --cov=./ --cov-report=xml:docs/coverage/coverage.xml --cov-config=.coveragerc"
testpaths = [
    "tests"
]

[tool.coverage.run]
branch = true
source = ["backend"]

[tool.coverage.paths]
source = [
    "backend/",
]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_also = [
    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self\\.debug",

    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",

    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",

    # Don't complain about abstract methods, they aren't run:
    "@(abc\\.)?abstractmethod",
]

ignore_errors = true

[tool.coverage.html]
directory = "docs/coverage/reports"
